apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: db-operators
  namespace: openshift-operators
spec:
  channel: stable
  name: db-operators
  source: sample-db-operators
  sourceNamespace: openshift-marketplace