# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache m2 repo
      id: cache-m2
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml' )}}
        
    - name: Build with Maven
      run: mvn -B -DskipTests install --file pom.xml
    
    - name: Create Release
      uses: google-github-actions/release-please-action@v2.19.2
      with:
        # GitHub token for creating and grooming release PRs, defaults to using secrets.GITHUB_TOKEN
        token: ${{ secrets.GH_WORKFLOW_PAT }}
        bump-minor-pre-major: true
        release-type: simple
