name: Release Artifacts

on:
  release:
    types:
      - "released"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Cache m2 repo"
        id: cache-m2
        uses: actions/cache@v2.1.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/.m2
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml' )}}

      - name: "Build with Maven"
        id: build-with-maven
        run: |
          ./mvnw -B -DskipTests install --file pom.xml
          artifact_version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -q \
                        -Dexpression=project.version -DforceStdout)
          echo "POM Version $pom_version"
          artifact_id=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -q \
                        -Dexpression=project.build.finalName -DforceStdout)
          artifact="$artifact_id-runner.jar"
          echo "Project Artifact $artifact"
          echo "::set-output name=artifact-version::$artifact_version"
          echo "::set-output name=artifact-id::$artifact_id"

      - name: "Quarkus App Tar ball"
        id: create-distro
        env:
          ARTIFACT_VERSION: ${{ steps.build-with-maven.outputs.artifact_version }}"
          ARTIFCT_ID: "${{ steps.build-with-maven.outputs.artifact-id }}"
        run: |
          TAR_FILE="${{ github.workspace }}/${ARTIFCT_ID}-${ARTIFACT_VERSION}.tar.gz"
          cd target \
            && tar -cvzf $TAR_FILE lib *-runner*
          echo "::set-output name=asset-name::${TAR_FILE}"

      - name: "Attach Artifacts to Release"
        uses: actions/github-script@v4.0.1
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          ASSET_FILE: "${{ steps.create-distro.asset-name }}"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const {TAG_NAME} = process.env
            const {ASSET_FILE} = process.env
            const {payload} = context

            const owner = payload.repository.owner.login
            const repo =  payload.repository.name

            console.log("Context Repository %s and Owner is %s",repo,owner)

             const { data } = await github.request(`GET /repos/${owner}/${repo}/releases/tags/{tag}`, {
               tag: TAG_NAME
             }).catch(err => {
               console.error("Error getting release %s", JSON.stringify(err.errors))
             })

             console.log("Release ->  %s",JSON.stringify(data))

             const upload_url = data.upload_url

             const contentLength = fs.statSync(ASSET_FILE).size;
             console.log("%s Content length=%s", ASSET_FILE, contentLength)

             const uploadAsset = await github.rest.repos.uploadReleaseAsset({
             url: upload_url,
             name: '${{ steps.build-with-maven.outputs.jar-asset }}',
             headers: {
               "content-type": "application/zip",
               "content-length": contentLength,
             },
             data: fs.readFileSync(ASSET_FILE)
             }).catch(err => {
               console.log("Error uploading asset %s", err)
             })

             console.log("Asset upload --> %s ",uploadAsset)
